# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmcta/Desktop/aula5_ex3/aula5_ex3.srcs/sources_1/bd/ex3/ip/ex3_clock_divider_1hz_0_0/ex3_clock_divider_1hz_0_0.xci
# IP: The module: 'ex3_clock_divider_1hz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmcta/Desktop/aula5_ex3/aula5_ex3.srcs/sources_1/bd/ex3/ip/ex3_clock_divider_1hz_0_0/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex3_clock_divider_1hz_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/fmcta/Desktop/aula5_ex3/aula5_ex3.srcs/sources_1/bd/ex3/ip/ex3_clock_divider_1hz_0_0/ex3_clock_divider_1hz_0_0.xci
# IP: The module: 'ex3_clock_divider_1hz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmcta/Desktop/aula5_ex3/aula5_ex3.srcs/sources_1/bd/ex3/ip/ex3_clock_divider_1hz_0_0/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex3_clock_divider_1hz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
