# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Praticas/Nexys4_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0/design_1_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0}]

# IP: bd/design_1/ip/design_1_clock_divider_0_0/design_1_clock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_divider_0_0 || ORIG_REF_NAME==design_1_clock_divider_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_0/design_1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1}]

# IP: bd/design_1/ip/design_1_xlslice_1_0/design_1_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_0 || ORIG_REF_NAME==design_1_xlslice_1_0}]

# IP: bd/design_1/ip/design_1_xlslice_1_1/design_1_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_1_1 || ORIG_REF_NAME==design_1_xlslice_1_1}]

# IP: bd/design_1/ip/design_1_sort_4bits_0_0/design_1_sort_4bits_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_4bits_0_0 || ORIG_REF_NAME==design_1_sort_4bits_0_0}]

# IP: bd/design_1/ip/design_1_sort_4bits_0_1/design_1_sort_4bits_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_4bits_0_1 || ORIG_REF_NAME==design_1_sort_4bits_0_1}]

# IP: bd/design_1/ip/design_1_sort_4bits_0_2/design_1_sort_4bits_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_4bits_0_2 || ORIG_REF_NAME==design_1_sort_4bits_0_2}]

# IP: bd/design_1/ip/design_1_sort_4bits_0_3/design_1_sort_4bits_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_4bits_0_3 || ORIG_REF_NAME==design_1_sort_4bits_0_3}]

# IP: bd/design_1/ip/design_1_sort_8bit_0_0/design_1_sort_8bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_8bit_0_0 || ORIG_REF_NAME==design_1_sort_8bit_0_0}]

# IP: bd/design_1/ip/design_1_sort_8bit_0_1/design_1_sort_8bit_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_8bit_0_1 || ORIG_REF_NAME==design_1_sort_8bit_0_1}]

# IP: bd/design_1/ip/design_1_xlslice_4_0/design_1_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_0 || ORIG_REF_NAME==design_1_xlslice_4_0}]

# IP: bd/design_1/ip/design_1_xlslice_4_1/design_1_xlslice_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_1 || ORIG_REF_NAME==design_1_xlslice_4_1}]

# IP: bd/design_1/ip/design_1_xlslice_4_2/design_1_xlslice_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_4_2 || ORIG_REF_NAME==design_1_xlslice_4_2}]

# IP: bd/design_1/ip/design_1_xlslice_5_0/design_1_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_5_0 || ORIG_REF_NAME==design_1_xlslice_5_0}]

# IP: bd/design_1/ip/design_1_sort_4bits_4_0/design_1_sort_4bits_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_4bits_4_0 || ORIG_REF_NAME==design_1_sort_4bits_4_0}]

# IP: bd/design_1/ip/design_1_sort_4bits_4_1/design_1_sort_4bits_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_4bits_4_1 || ORIG_REF_NAME==design_1_sort_4bits_4_1}]

# IP: bd/design_1/ip/design_1_sort_4bits_4_2/design_1_sort_4bits_4_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_4bits_4_2 || ORIG_REF_NAME==design_1_sort_4bits_4_2}]

# IP: bd/design_1/ip/design_1_sort_4bits_4_3/design_1_sort_4bits_4_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_4bits_4_3 || ORIG_REF_NAME==design_1_sort_4bits_4_3}]

# IP: bd/design_1/ip/design_1_xlconcat_0_0/design_1_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0}]

# IP: bd/design_1/ip/design_1_xlconcat_0_1/design_1_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_1 || ORIG_REF_NAME==design_1_xlconcat_0_1}]

# IP: bd/design_1/ip/design_1_sort_gen_0_0/design_1_sort_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_sort_gen_0_0 || ORIG_REF_NAME==design_1_sort_gen_0_0}]

# IP: bd/design_1/ip/design_1_valuesSorted_0_0/design_1_valuesSorted_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_valuesSorted_0_0 || ORIG_REF_NAME==design_1_valuesSorted_0_0}]

# IP: bd/design_1/ip/design_1_xlslice_8_0/design_1_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_8_0 || ORIG_REF_NAME==design_1_xlslice_8_0}]

# IP: bd/design_1/ip/design_1_xlslice_8_2/design_1_xlslice_8_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlslice_8_2 || ORIG_REF_NAME==design_1_xlslice_8_2}]

# IP: bd/design_1/ip/design_1_EightDisplayControl_0_0/design_1_EightDisplayControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_EightDisplayControl_0_0 || ORIG_REF_NAME==design_1_EightDisplayControl_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_1_0/design_1_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_1_0 || ORIG_REF_NAME==design_1_xlconstant_1_0}]

# XDC: bd/design_1/design_1_ooc.xdc
