# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Users/jgnro/Desktop/UA/4A2S/4A2S/CR/Praticas/03/34-Hamming/34-Hamming.cache/wt [current_project]
set_property parent.project_path D:/Users/jgnro/Desktop/UA/4A2S/4A2S/CR/Praticas/03/34-Hamming/34-Hamming.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/Users/jgnro/Desktop/UA/4A2S/4A2S/CR/Praticas/03/34-Hamming/34-Hamming.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib D:/Users/jgnro/Desktop/UA/4A2S/4A2S/CR/Praticas/03/34-Hamming/34-Hamming.srcs/sources_1/new/hamming.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Users/jgnro/Desktop/UA/4A2S/4A2S/CR/Praticas/03/34-Hamming/34-Hamming.srcs/constrs_1/imports/N4/Nexys4_Master.xdc
set_property used_in_implementation false [get_files D:/Users/jgnro/Desktop/UA/4A2S/4A2S/CR/Praticas/03/34-Hamming/34-Hamming.srcs/constrs_1/imports/N4/Nexys4_Master.xdc]


synth_design -top hamming -part xc7a100tcsg324-1


write_checkpoint -force -noxdef hamming.dcp

catch { report_utilization -file hamming_utilization_synth.rpt -pb hamming_utilization_synth.pb }
