# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Projeto/ProjetoFinal/MP_ToDisplays/MP_ToDisplays.srcs/sources_1/bd/DebUART/ip/DebUART_ilmb_bram_if_cntlr_0/DebUART_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'DebUART_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Projeto/ProjetoFinal/MP_ToDisplays/MP_ToDisplays.srcs/sources_1/bd/DebUART/ip/DebUART_ilmb_bram_if_cntlr_0/DebUART_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DebUART_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Projeto/ProjetoFinal/MP_ToDisplays/MP_ToDisplays.srcs/sources_1/bd/DebUART/ip/DebUART_ilmb_bram_if_cntlr_0/DebUART_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'DebUART_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Projeto/ProjetoFinal/MP_ToDisplays/MP_ToDisplays.srcs/sources_1/bd/DebUART/ip/DebUART_ilmb_bram_if_cntlr_0/DebUART_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DebUART_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
