# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/fmcta/Desktop/Filipe/Universidade/CR/Nexys4_Master.xdc

# Block Designs: bd/ex2/ex2.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2 || ORIG_REF_NAME==ex2}]

# IP: bd/ex2/ip/ex2_clock_divider_0_0_1/ex2_clock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_clock_divider_0_0 || ORIG_REF_NAME==ex2_clock_divider_0_0}]

# IP: bd/ex2/ip/ex2_BinToBCD16_0_0_1/ex2_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_BinToBCD16_0_0 || ORIG_REF_NAME==ex2_BinToBCD16_0_0}]

# IP: bd/ex2/ip/ex2_xlconstant_0_0_1/ex2_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_xlconstant_0_0 || ORIG_REF_NAME==ex2_xlconstant_0_0}]

# IP: bd/ex2/ip/ex2_GreatestMaximumDivisor_0_1_2/ex2_GreatestMaximumDivisor_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_GreatestMaximumDivisor_0_1 || ORIG_REF_NAME==ex2_GreatestMaximumDivisor_0_1}]

# IP: bd/ex2/ip/ex2_Decimal_to_Displays_3_0_0/ex2_Decimal_to_Displays_3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex2_Decimal_to_Displays_3_0_0 || ORIG_REF_NAME==ex2_Decimal_to_Displays_3_0_0}]

# XDC: bd/ex2/ex2_ooc.xdc
