# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Praticas/Aula6/Ex1/Ex1.srcs/sources_1/bd/design_1/ip/design_1_selectAddress_0_0/design_1_selectAddress_0_0.xci
# IP: The module: 'design_1_selectAddress_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Praticas/Aula6/Ex1/Ex1.srcs/sources_1/bd/design_1/ip/design_1_selectAddress_0_0/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_selectAddress_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Praticas/Aula6/Ex1/Ex1.srcs/sources_1/bd/design_1/ip/design_1_selectAddress_0_0/design_1_selectAddress_0_0.xci
# IP: The module: 'design_1_selectAddress_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Praticas/Aula6/Ex1/Ex1.srcs/sources_1/bd/design_1/ip/design_1_selectAddress_0_0/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_selectAddress_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
