# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/fmcta/Desktop/Filipe/Universidade/CR/Nexys4_Master.xdc

# Block Designs: bd/ex3/ex3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3 || ORIG_REF_NAME==ex3}]

# IP: bd/ex3/ip/ex3_blk_mem_gen_0_0/ex3_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_blk_mem_gen_0_0 || ORIG_REF_NAME==ex3_blk_mem_gen_0_0}]

# IP: bd/ex3/ip/ex3_Hamming_0_0/ex3_Hamming_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_Hamming_0_0 || ORIG_REF_NAME==ex3_Hamming_0_0}]

# IP: bd/ex3/ip/ex3_BinToBCD16_0_0/ex3_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_BinToBCD16_0_0 || ORIG_REF_NAME==ex3_BinToBCD16_0_0}]

# IP: bd/ex3/ip/ex3_addr_select_0_0/ex3_addr_select_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_addr_select_0_0 || ORIG_REF_NAME==ex3_addr_select_0_0}]

# IP: bd/ex3/ip/ex3_EightDispControl_0_0/ex3_EightDispControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_EightDispControl_0_0 || ORIG_REF_NAME==ex3_EightDispControl_0_0}]

# IP: bd/ex3/ip/ex3_clock_divider_1hz_0_0/ex3_clock_divider_1hz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_clock_divider_1hz_0_0 || ORIG_REF_NAME==ex3_clock_divider_1hz_0_0}]

# IP: bd/ex3/ip/ex3_xlconstant_0_0/ex3_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_xlconstant_0_0 || ORIG_REF_NAME==ex3_xlconstant_0_0}]

# IP: bd/ex3/ip/ex3_xlconstant_1_0/ex3_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_xlconstant_1_0 || ORIG_REF_NAME==ex3_xlconstant_1_0}]

# IP: bd/ex3/ip/ex3_xlconstant_2_0/ex3_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_xlconstant_2_0 || ORIG_REF_NAME==ex3_xlconstant_2_0}]

# XDC: bd/ex3/ex3_ooc.xdc
