# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/Utilizador/Desktop/Universidade/4_ano/2_semestre/CR/Praticas/Nexys4_Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1}]

# IP: bd/design_1/ip/design_1_clock_divider_0_0/design_1_clock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clock_divider_0_0 || ORIG_REF_NAME==design_1_clock_divider_0_0}]

# IP: bd/design_1/ip/design_1_GreatestMaximumDivisor_0_0/design_1_GreatestMaximumDivisor_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_GreatestMaximumDivisor_0_0 || ORIG_REF_NAME==design_1_GreatestMaximumDivisor_0_0}]

# IP: bd/design_1/ip/design_1_BinToBCD16_0_0/design_1_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_BinToBCD16_0_0 || ORIG_REF_NAME==design_1_BinToBCD16_0_0}]

# IP: bd/design_1/ip/design_1_Decimal_to_Displays_3_0_0/design_1_Decimal_to_Displays_3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_Decimal_to_Displays_3_0_0 || ORIG_REF_NAME==design_1_Decimal_to_Displays_3_0_0}]

# IP: bd/design_1/ip/design_1_xlconstant_0_1/design_1_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_1 || ORIG_REF_NAME==design_1_xlconstant_0_1}]

# XDC: bd/design_1/design_1_ooc.xdc
