# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmcta/aula3_final/aula3_final.srcs/sources_1/bd/ex1/ip/ex1_contador_0_2/ex1_contador_0_2.xci
# IP: The module: 'ex1_contador_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmcta/aula3_final/aula3_final.srcs/sources_1/bd/ex1/ip/ex1_contador_0_2/Desktop/Filipe/Universidade/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex1_contador_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/fmcta/aula3_final/aula3_final.srcs/sources_1/bd/ex1/ip/ex1_contador_0_2/ex1_contador_0_2.xci
# IP: The module: 'ex1_contador_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmcta/aula3_final/aula3_final.srcs/sources_1/bd/ex1/ip/ex1_contador_0_2/Desktop/Filipe/Universidade/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex1_contador_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
