# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex1/ex1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1 || ORIG_REF_NAME==ex1}]

# IP: bd/ex1/ip/ex1_clock_divider_0_0/ex1_clock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_clock_divider_0_0 || ORIG_REF_NAME==ex1_clock_divider_0_0}]

# IP: bd/ex1/ip/ex1_xlconstant_0_0/ex1_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_xlconstant_0_0 || ORIG_REF_NAME==ex1_xlconstant_0_0}]

# IP: bd/ex1/ip/ex1_Decimal_to_Displays_0_0/ex1_Decimal_to_Displays_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_Decimal_to_Displays_0_0 || ORIG_REF_NAME==ex1_Decimal_to_Displays_0_0}]

# IP: bd/ex1/ip/ex1_contador_0_2/ex1_contador_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_contador_0_2 || ORIG_REF_NAME==ex1_contador_0_2}]

# IP: bd/ex1/ip/ex1_BinToBCD16_0_0/ex1_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex1_BinToBCD16_0_0 || ORIG_REF_NAME==ex1_BinToBCD16_0_0}]

# XDC: bd/ex1/ip/ex1_contador_0_2/Desktop/Filipe/Universidade/CR/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ex1_contador_0_2 || ORIG_REF_NAME==ex1_contador_0_2}] {/U0 }]/U0 ]]

# XDC: bd/ex1/ex1_ooc.xdc
