# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/ex3_contador1000Bits_0_1.xci
# IP: The module: 'ex3_contador1000Bits_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_Decimal_to_Displays_4_0_0/ex3_Decimal_to_Displays_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_Decimal_to_Displays_4_0_0 || ORIG_REF_NAME==ex3_Decimal_to_Displays_4_0_0}]

# IP: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_BinToBCD16_0_0/ex3_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_BinToBCD16_0_0 || ORIG_REF_NAME==ex3_BinToBCD16_0_0}]

# IP: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_RanGen_0_0/ex3_RanGen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_RanGen_0_0 || ORIG_REF_NAME==ex3_RanGen_0_0}]

# XDC: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_Decimal_to_Displays_4_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ex3_Decimal_to_Displays_4_0_0 || ORIG_REF_NAME==ex3_Decimal_to_Displays_4_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_RanGen_0_0/src/Nexys4_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ex3_RanGen_0_0 || ORIG_REF_NAME==ex3_RanGen_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex3_contador1000Bits_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/ex3_contador1000Bits_0_1.xci
# IP: The module: 'ex3_contador1000Bits_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_Decimal_to_Displays_4_0_0/ex3_Decimal_to_Displays_4_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_Decimal_to_Displays_4_0_0 || ORIG_REF_NAME==ex3_Decimal_to_Displays_4_0_0}]

# IP: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_BinToBCD16_0_0/ex3_BinToBCD16_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_BinToBCD16_0_0 || ORIG_REF_NAME==ex3_BinToBCD16_0_0}]

# IP: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_RanGen_0_0/ex3_RanGen_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_RanGen_0_0 || ORIG_REF_NAME==ex3_RanGen_0_0}]

# XDC: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_Decimal_to_Displays_4_0_0/src/Nexys4_Master.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ex3_Decimal_to_Displays_4_0_0 || ORIG_REF_NAME==ex3_Decimal_to_Displays_4_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/ex3_RanGen_0_0/src/Nexys4_Master.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==ex3_RanGen_0_0 || ORIG_REF_NAME==ex3_RanGen_0_0}] {/U0 }]/U0 ]]

# XDC: c:/Users/fmcta/Desktop/project_1/project_1.srcs/sources_1/bd/ex3/ip/ex3_contador1000Bits_0_1/src/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex3_contador1000Bits_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
