# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CR/Nexys4_Master.xdc

# Block Designs: bd/ex3/ex3.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3 || ORIG_REF_NAME==ex3}]

# IP: bd/ex3/ip/ex3_BinToBCD16_0_0/ex3_BinToBCD16_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_BinToBCD16_0_0 || ORIG_REF_NAME==ex3_BinToBCD16_0_0}]

# IP: bd/ex3/ip/ex3_RanGen_0_0/ex3_RanGen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_RanGen_0_0 || ORIG_REF_NAME==ex3_RanGen_0_0}]

# IP: bd/ex3/ip/ex3_clock_divider_0_0/ex3_clock_divider_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_clock_divider_0_0 || ORIG_REF_NAME==ex3_clock_divider_0_0}]

# IP: bd/ex3/ip/ex3_Decimal_to_Displays_4_0_0/ex3_Decimal_to_Displays_4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_Decimal_to_Displays_4_0_0 || ORIG_REF_NAME==ex3_Decimal_to_Displays_4_0_0}]

# IP: bd/ex3/ip/ex3_xlconstant_0_0/ex3_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_xlconstant_0_0 || ORIG_REF_NAME==ex3_xlconstant_0_0}]

# IP: bd/ex3/ip/ex3_contador1000Bits_0_1/ex3_contador1000Bits_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ex3_contador1000Bits_0_1 || ORIG_REF_NAME==ex3_contador1000Bits_0_1}]

# XDC: bd/ex3/ex3_ooc.xdc
