# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/fmcta/Desktop/aula3_ex2/aula3_ex2.srcs/sources_1/bd/ex2/ip/ex2_GreatestMaximumDivisor_0_1_2/ex2_GreatestMaximumDivisor_0_1.xci
# IP: The module: 'ex2_GreatestMaximumDivisor_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmcta/Desktop/aula3_ex2/aula3_ex2.srcs/sources_1/bd/ex2/ip/ex2_GreatestMaximumDivisor_0_1_2/Desktop/Filipe/Universidade/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex2_GreatestMaximumDivisor_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/Users/fmcta/Desktop/aula3_ex2/aula3_ex2.srcs/sources_1/bd/ex2/ip/ex2_GreatestMaximumDivisor_0_1_2/ex2_GreatestMaximumDivisor_0_1.xci
# IP: The module: 'ex2_GreatestMaximumDivisor_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/fmcta/Desktop/aula3_ex2/aula3_ex2.srcs/sources_1/bd/ex2/ip/ex2_GreatestMaximumDivisor_0_1_2/Desktop/Filipe/Universidade/CR/Nexys4_Master.xdc
# XDC: The top module name and the constraint reference have the same name: 'ex2_GreatestMaximumDivisor_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
